from Discos.Comandos.mount import ParticionesMontadas
from Reportes.Comandos.bm_block import reporteBM_BLOCK
from Reportes.Comandos.bm_inode import reporteBM_INODE
from Reportes.Comandos.disk import reporteDISK
from Reportes.Comandos.file import reporteFILE
from Reportes.Comandos.mbr import reporteMBR
from Reportes.Comandos.sb import reporteSB
from Reportes.Comandos.tree import reporteTREE
from Utilidades.utilidades import *